"""Contratos mínimos compartidos por persistencia local y Supabase."""

from __future__ import annotations

from typing import Any, Protocol


class SessionRepository(Protocol):
    def get(self, participant_id: str) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def list_for_evaluator(self, user_id: str) -> list[dict[str, Any]]: ...
    def save(self, record: dict[str, Any]) -> None: ...
    def audit_access(self, actor_id: str, actor_role: str, action: str, target_type: str, target_id: str = "") -> None: ...


class LearningOpportunityRepository(Protocol):
    def get(self, activity_id: str) -> dict[str, Any] | None: ...
    def save_once(self, activity_id: str, record: dict[str, Any]) -> None: ...
