"""Contratos mínimos compartidos por persistencia local y Supabase."""

from __future__ import annotations

from typing import Any, Protocol


class SessionRepository(Protocol):
    def get(self, participant_id: str, activity_session_id: str = "") -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def list_for_evaluator(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_activity_session(self, session_code: str) -> dict[str, Any] | None: ...
    def create_activity_session(self, title: str, created_by: str, evaluator_id: str = "") -> dict[str, Any]: ...
    def list_activity_sessions_for_creator(self, user_id: str) -> list[dict[str, Any]]: ...
    def list_activity_sessions_for_evaluator(self, user_id: str) -> list[dict[str, Any]]: ...
    def list_participants(self, activity_session_id: str) -> list[dict[str, Any]]: ...
    def list_evaluators(self) -> list[dict[str, str]]: ...
    def set_activity_session_status(self, session_code: str, status: str) -> None: ...
    def save(self, record: dict[str, Any]) -> None: ...
    def audit_access(self, actor_id: str, actor_role: str, action: str, target_type: str, target_id: str = "") -> None: ...


class LearningOpportunityRepository(Protocol):
    def get(self, activity_id: str) -> dict[str, Any] | None: ...
    def save_once(self, activity_id: str, record: dict[str, Any]) -> None: ...
